### ISSUE TITLE
Can't send CSV email - webpage not available

### ISSUE THREAD

**Issue by mmier** [JamesFowler42/morpheuz20#6]
When I click on Mail button, the following error is displayed:

Webpage not availavle
The webpage at mailto:?subject=Morpheus-2014-03-20.csv?body....
might be temporaty down or it may have moved permanently to a new address

Android 4.2
Pebble Android 2.0.14
Pebble Watch: 2.0.2

**Comment by JamesFowler42** [comment]
Sadly this is an android related problem that actually cannot be addressed by code changes within Morpheuz. Pushover integration now provides an alternative route to exporting the data.
